// Code generated by MockGen. DO NOT EDIT.
// Source: modules/prompt/domain/repo/generate_record.go
//
// Generated by this command:
//
//	mockgen -source=modules/prompt/domain/repo/generate_record.go -destination=modules/prompt/domain/repo/mocks/generate_record_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIGenerateRecordRepo is a mock of IGenerateRecordRepo interface.
type MockIGenerateRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIGenerateRecordRepoMockRecorder
}

// MockIGenerateRecordRepoMockRecorder is the mock recorder for MockIGenerateRecordRepo.
type MockIGenerateRecordRepoMockRecorder struct {
	mock *MockIGenerateRecordRepo
}

// NewMockIGenerateRecordRepo creates a new mock instance.
func NewMockIGenerateRecordRepo(ctrl *gomock.Controller) *MockIGenerateRecordRepo {
	mock := &MockIGenerateRecordRepo{ctrl: ctrl}
	mock.recorder = &MockIGenerateRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGenerateRecordRepo) EXPECT() *MockIGenerateRecordRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIGenerateRecordRepo) Create(ctx context.Context, record *entity.PromptGenerateRecord) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, record)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIGenerateRecordRepoMockRecorder) Create(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIGenerateRecordRepo)(nil).Create), ctx, record)
}

// Finish mocks base method.
func (m *MockIGenerateRecordRepo) Finish(ctx context.Context, record *entity.PromptGenerateRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockIGenerateRecordRepoMockRecorder) Finish(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockIGenerateRecordRepo)(nil).Finish), ctx, record)
}

// UpdateFeedback mocks base method.
func (m *MockIGenerateRecordRepo) UpdateFeedback(ctx context.Context, param repo.UpdateGenerateRecordParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedback", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedback indicates an expected call of UpdateFeedback.
func (mr *MockIGenerateRecordRepoMockRecorder) UpdateFeedback(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedback", reflect.TypeOf((*MockIGenerateRecordRepo)(nil).UpdateFeedback), ctx, param)
}
